### ISSUE TITLE
API_SANDBOX trailing slash

### ISSUE THREAD

**Issue by antoineleclair** [synapsepayments/synapse_pay-python#1]
https://github.com/synapsepayments/synapse_pay-python/blob/7d318854166646a4a7b6fbed8c07803c22c2cfc6/synapse_pay/__init__.py#L2

Even though the `SANDBOX_API` variable does not seem to be used in the code, it does not have a trailing slash like the `API_BASE` a few lines below.

https://github.com/synapsepayments/synapse_pay-python/blob/7d318854166646a4a7b6fbed8c07803c22c2cfc6/synapse_pay/__init__.py#L6

**Comment by joncalhoun** [comment]
Hi @antoineleclair 

The sandbox api var can be used to easily switch to sandbox mode. eg:

``` python
synapse_pay.API_BASE = synapse_pay.API_SANDBOX
```

Thanks for pointing out the URL discrepancy. It shouldn't actually affect the code (all paths are defined with a preceding '/' char), but we will clean it in the next release.

**Comment by joncalhoun** [comment]
This should be resolved now.
